/**
 * Base Scenario Schema
 * Common fields for all scenario types
 * 
 * @author Ying Wang
 * @date 2026-02-12
 * @version 1.0
 */

export type ScenarioType = "ctf" | "quiz" | "hands-on lab" | "simulated attack";
export type DifficultyLevel = "beginner" | "intermediate" | "advanced" | "expert";
export type ScenarioStatus = "draft" | "pending_review" | "published" | "archived";

export interface BaseScenario {
  scenario_id: string; // UUID
  scenario_type: ScenarioType;
  
  basic_info: BasicInfo;
  metadata: ScenarioMetadata;
}

export interface BasicInfo {
  title: string; // 1-200 characters
  topic: string; // e.g., "SQL Injection", "Packet Sniffing"
  subtopic?: string; // e.g., "Union-based", "ARP Spoofing"
  difficulty: DifficultyLevel;
  estimated_time: number; // minutes
  learning_objectives: string[]; // at least 1
  tags?: string[]; // optional keywords
}

export interface ScenarioMetadata {
  created_at: string; // ISO 8601 datetime
  updated_at: string; // ISO 8601 datetime
  created_by: string; // instructor id or email
  version: number; // incremental version number
  status: ScenarioStatus;
  llm_generated: boolean; // was this generated by LLM?
}

/**
 * LLM Configuration
 * Settings used for AI-assisted content generation
 */
export interface LLMConfig {
  // Preset selection
  preset: "beginner-friendly" | "balanced" | "challenge" | "custom";
  
  // Core parameters (0.0 - 1.0)
  creativity: number; // How varied/creative the responses are
  hint_detail_level: number; // How detailed the hints are
  feedback_detail_level: number; // How detailed the feedback is
  explanation_depth: number; // Depth of explanations
  
  // Content configuration
  hint_count: number; // 3-7
  
  // Style parameters
  narrative_style: "realistic" | "gamified" | "academic";
  communication_style: "professional" | "friendly" | "mentor" | "peer";
}

/**
 * Default LLM configurations for each preset
 */
export const LLM_PRESET_DEFAULTS: Record<string, Partial<LLMConfig>> = {
  "beginner-friendly": {
    creativity: 0.5,
    hint_detail_level: 0.8,
    feedback_detail_level: 0.9,
    explanation_depth: 0.8,
    hint_count: 5,
    narrative_style: "gamified",
    communication_style: "friendly"
  },
  "balanced": {
    creativity: 0.6,
    hint_detail_level: 0.6,
    feedback_detail_level: 0.7,
    explanation_depth: 0.6,
    hint_count: 5,
    narrative_style: "realistic",
    communication_style: "friendly"
  },
  "challenge": {
    creativity: 0.7,
    hint_detail_level: 0.3,
    feedback_detail_level: 0.5,
    explanation_depth: 0.4,
    hint_count: 3,
    narrative_style: "realistic",
    communication_style: "professional"
  }
};